{
   "last_tab":"",
   "theme-type":"1",
   "layout":"fullwidth",
   "left-sidebar":"",
   "right-sidebar":"",
   "logo":{
      "url":"<?php echo get_template_directory_uri(); ?>/images/logo.png",
      "id":"",
      "height":"26",
      "width":"",
      "thumbnail":""
   },
   "logo_4":{
      "url":"<?php echo get_template_directory_uri(); ?>/images/logo_4.png",
      "id":"",
      "height":"",
      "width":"",
      "thumbnail":""
   },
   "logo_5":{
      "url":"<?php echo get_template_directory_uri(); ?>/images/logo_5.png",
      "id":"",
      "height":"",
      "width":"",
      "thumbnail":""
   },
   "favicon":{
      "url":"<?php echo get_template_directory_uri(); ?>/images/favicon.ico",
      "id":"",
      "height":"",
      "width":"",
      "thumbnail":""
   },
   "js-code":"jQuery(document).ready(function(){});",
   "compile-css":"",
   "general-bg":{
      "background-color":"#f2f2f2",
      "background-repeat":"no-repeat",
      "background-size":"inherit",
      "background-attachment":"inherit",
      "background-position":"center center",
      "background-image":"",
      "media":{
         "id":"",
         "height":"",
         "width":"",
         "thumbnail":""
      }
   },
   "general-font":{
      "font-family":"Lato",
      "font-options":"",
      "google":"1",
      "font-weight":"400",
      "font-style":"",
      "font-size":"14px",
      "line-height":"23px",
      "color":"#787878"
   },
   "primary-color":"#ff2759",
   "highlight-color":"#700877",
   "footer-bg-color":"#0c000e",
   "footer-bg":{
      "background-repeat":"no-repeat",
      "background-size":"cover",
      "background-attachment":"inherit",
      "background-position":"center center",
      "background-image":"<?php echo get_template_directory_uri(); ?>/images/bg-footer-v1.jpg",
      "media":{
         "id":"",
         "height":"",
         "width":"",
         "thumbnail":""
      }
   },
   "breadcrumbs-bg":{
      "background-repeat":"no-repeat",
      "background-size":"cover",
      "background-attachment":"inherit",
      "background-position":"center center",
      "background-image":"<?php echo get_template_directory_uri(); ?>/images/background/bg-breadcrumb.jpg",
      "media":{
         "id":"",
         "height":"",
         "width":"",
         "thumbnail":""
      }
   },
   "h1-font":{
      "font-family":"Lato",
      "font-options":"",
      "google":"1",
      "font-size":"48px",
      "color":"#000000"
   },
   "h2-font":{
      "font-family":"Lato",
      "font-options":"",
      "google":"1",
      "font-size":"36px",
      "color":"#000000"
   },
   "h3-font":{
      "font-family":"Lato",
      "font-options":"",
      "google":"1",
      "font-size":"20px",
      "color":"#000000"
   },
   "h4-font":{
      "font-family":"Lato",
      "font-options":"",
      "google":"1",
      "font-size":"18px",
      "color":"#000000"
   },
   "h5-font":{
      "font-family":"Lato",
      "font-options":"",
      "google":"1",
      "font-size":"16px",
      "color":"#000000"
   },
   "h6-font":{
      "font-family":"Lato",
      "font-options":"",
      "google":"1",
      "font-size":"10px",
      "color":"#000000"
   },
   "custom-css-code":"",
   "header-type":"1",
   "header-link":"#",
   "header-address":"Brooklyn, NY 10036, United States",
   "header-phone-number":"(+84)1234-5678",
   "header-search":"1",
   "header-myaccount":"1",
   "header-cart":"1",
   "header-sticky":"1",
   "logo-header-sticky":{
      "url":"<?php echo get_template_directory_uri(); ?>/images/sticky-logo.png",
      "id":"",
      "height":"",
      "width":"",
      "thumbnail":""
   },
   "footer-type":"1",
   "footer-copyright":"&copy; Riven 2016. All Rights Reserved. Designed by <a target=\"_blank\" href=\"http:\/\/arrowhitech.com\">AHT Studio<\/a>",
   "show-top-footer":"1",
   "post-layout":"fullwidth",
   "left-post-sidebar":"",
   "right-post-sidebar":"blog-sidebar",
   "blog-archive-column":"1",
   "post-banner":"",
   "blog-title":"Blog",
   "event-layout":"fullwidth",
   "left-event-sidebar":"",
   "right-event-sidebar":"event-sidebar",
   "event-title":"Event",
   "portfolio-layout":"wide",
   "left-portfolio-sidebar":"",
   "right-portfolio-sidebar":"",
   "portfolio-banner":"",
   "portfolio-title":"Project",
   "portfolio-single-layout":"fullwidth",
   "shop-layout":"fullwidth",
   "left-shop-sidebar":"shop-sidebar",
   "right-shop-sidebar":"",
   "category-item":"8,16,24",
   "product-cols":"4",
   "single-product-layout":"fullwidth",
   "left-single-product-sidebar":"",
   "right-single-product-sidebar":"single-product-sidebar",
   "social-facebook":"#",
   "social-google":"#",
   "social-twitter":"#",
   "social-linkedin":"#",
   "social-pinterest":"#",
   "social-youtube":"#",
   "redux-backup":"1"
}